app:
  host: "127.0.0.1"
  port: 8050
  debug: false
  quiet: false
  detach: false
  administrative: false

ui:
  themes:
    table:
      table_theme: "ag-theme-alpine"
      bg_main: "white"
      bg_2: "white"
      bg_header: "white"
      fg_main: "black"
      fg_header: "black"
      sep: "silver"
    row:
      mark: ""
    cell:
      posvalue: null
      negvalue: null
      active_bg: ""
      selected_bg: ""
      hover_bg: ""
    footer:
      sig1: ""
      sig2: ""
    balance:
      col1_sep: ""
      year: ""
      header_year: ""
      quarter_sep: ""
      current_sep: ""
      col_t52: ""
      header_t52: ""
      col_current: ""
      header_current: ""
    notepaper:
      bg: "white"
      fg: "black"
      border: ""
      link: "blue"
    rating_scale:
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
    alt_rating_scale:
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
      - ""
  log:
    col_order_asset: [1, 2, 3, 0, 0, 0, 0, -2, 8]
    col_order_note: [0, 0, 0, 1, 2, 7, 0, 8]
    col_widths: [140, 70, 0, 70, 50, 90, 50, 30, 80, 170, 150, 110, 170, 150, 110, 80, 110, 110, 80, 120, 170, 160, 160, 160, 160]
  note:
    mathjax: true
    cell_variable_formatter: true
    file_drop_cloner: "own"
  balance:
    side_init_balance_value: true
    t52w: true
    current: true
    years: true
    quarters: true
  statistics:
    sun_max_depth: 3
    group_default: [true, false, true, false, true]
    performance:
      size_slider: 6
      steps: 12
      trailing_frame: "month"
      trailing_interval: 1
      range: "1y"
      hypothesis_per: true
  pagination:
    per_page: 100
  time_format_transaction: "%Y-%m-%d %H:%M:%S"
  time_format_history: "%Y-%m-%d %H:%M:%S"
  bottom_bar_distance_bottom: "10px"
  bottom_bar_distance_right: "10px"
  c1_width: "50%"
  grid_row3_height: 200

storage:
  backend: "sqlalchemy"
  url: "sqlite:///journal.db"
  plugin: null

logging:
  rotation_mb: 500
  retention_days: 10

profiles:
  home_folder: "Trading-Journals.srtj"
  prefix: "%"
  demo_folder: "#demo"