"""Startup operations for SRTJ."""

import sys
import webbrowser
from os import environ, system
from pathlib import Path
from re import DOTALL, search

from logprise import logger

from . import __ini__, _files
from .autoclean import autocleaner
from .cache_manager import color_cache, column_cache
from .data_manager import data_manager
from .loader import config
from .path_manager import paths
from .profile_manager import profile_manager
from .server_manager import server_manager
from .ui_utils import ui_utils


class StartupManager:
    """Handles startup operations."""

    def __init__(self):
        self.call_gui = None

    def initialize(self):
        """Initialize the application."""
        # Handle early exit commands
        if self._handle_early_exit():
            return

        # Load profile
        profile_name = self._get_profile_name()
        profile_manager.load_profile(profile_name)

        # Reload config with profile
        config.reload(profile_manager.profile_folder)

        # Refresh paths after profile is loaded
        paths.refresh()

        # Initialize data
        data_manager._init_data()

        # Run autoclean
        autocleaner.run(data_manager.journal_data)

        # Set up GUI caller
        self._setup_gui_caller()

        # Write config files
        self._write_rc_js()
        self._write_rc_css()

        logger.info(f"Initialized with profile: {profile_manager.profile_name or 'default'}")

    def _handle_early_exit(self) -> bool:
        """Handle commands that should exit early."""
        if not __ini__.cmdl.DIRECTIVES:
            if __ini__.cmdl.FLAGS.ping:
                sys.exit(0 if server_manager.ping() else 1)
            elif __ini__.cmdl.FLAGS.kill:
                sys.exit(0 if server_manager.kill() else 1)
            return False

        cmd = __ini__.cmdl.DIRECTIVES[0]

        if cmd == "version":
            from .. import __version__
            print(__version__)
            sys.exit(0)
        elif cmd == "help":
            print("SRTJ Help - See documentation")
            sys.exit(0)

        return False

    def _get_profile_name(self) -> str | None:
        """Get profile name from environment or command line."""
        if profile := environ.get("SRTJ"):
            return profile

        if __ini__.cmdl.DIRECTIVES:
            if __ini__.cmdl.DIRECTIVES[0] == "/":
                __ini__.cmdl.DIRECTIVES.pop(0)
                if __ini__.cmdl.DIRECTIVES:
                    return __ini__.cmdl.DIRECTIVES.pop(0)
            elif not __ini__.cmdl.DIRECTIVES[0].startswith("/"):
                return __ini__.cmdl.DIRECTIVES.pop(0)

        return None

    def _setup_gui_caller(self):
        """Set up GUI calling mechanism."""
        call_gui_file = profile_manager.profiles_home / _files.file_call_gui

        if not call_gui_file.exists():
            logger.debug("No call_gui file found")
            return

        content = call_gui_file.read_text()

        if not (start_section := search(r"(?:(?:\n|^)\[start])(((?!\n\[).)*)", content, DOTALL)):
            return

        proc = None
        for line in start_section.group(1).splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                proc = line
                break

        if proc == "*none":
            return
        elif proc == "*pop":
            self.call_gui = lambda: webbrowser.open_new_tab(config.app.url)
        elif proc:
            # Handle parameters
            if params_section := search(rf"(?:(?:\n|^)\[start\.{proc}\.params])(((?!\n\[).)*)", content, DOTALL):
                for line in params_section.group(1).splitlines():
                    line = line.strip()
                    if line and not line.startswith("#"):
                        proc += f" {line}"

                proc = proc.format(
                    **{
                        "*url": config.app.url,
                        "*profile-root": str(profile_manager.profile_folder),
                        "*user-home": str(Path.home()),
                    }
                )
            else:
                proc += f" {config.app.url}"

            self.call_gui = lambda: system(proc)

    def _write_rc_js(self):
        """Write JavaScript configuration file."""
        content = f"""// Auto-generated by SRTJ
const gridDefWidthScale={config.ui.grid.def_width_scale};
const gridMinWidthScale={config.ui.grid.min_width_scale};
const gridRow3Height={config.ui.grid.row3_height};
const gridSideSizeInitValue={config.ui.grid.side_size_init_value};
const c1Width="{config.ui.grid.c1_width}";
const c2Width="{config.ui.grid.c2_width}";
const sideInitStatisticValue={config.ui.grid.side_init_statistic_value};
const dateFormat="{config.ui.date_format}";
const timeFormatTransaction="{config.ui.time_format_transaction}";
const ccCopy="{config.ui.bind_key_codes[0]}";
const ccCut="{config.ui.bind_key_codes[1]}";
const ccPaste="{config.ui.bind_key_codes[2]}";
const ccCopyRow1="{config.ui.bind_key_codes[3]}";
const ccCopyRow2="{config.ui.bind_key_codes[4]}";
const ccCopyRow3="{config.ui.bind_key_codes[5]}";
const ccAComplete="{config.ui.bind_key_codes[6]}";
const ccNote="{config.ui.bind_key_codes[7]}";
const ccNoteBack="{config.ui.bind_key_codes[8]}";
const ccMark="{config.ui.bind_key_codes[9]}";
const noteCellVariableFormatter={int(config.notes.cell_variable_formatter)};
const noteUnifying={int(config.notes.unifying)};
const noteLinkDropPattern=/{config.notes.link_drop_pattern}/;
const notePathDropPattern=/{config.notes.path_drop_pattern}/;
const columnStateCache={int(bool(column_cache.data))};
const iniColumnState={int(column_cache.ini_state)};
"""
        paths.rc_js.write_text(content)

    def _write_rc_css(self):
        """Write CSS configuration file."""
        css_content = ui_utils.generate_css()
        paths.rc_css.write_text(css_content)


startup = StartupManager()